name: humanoid

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pip
  - numpy=1.21.6
  - scipy=1.7.3
  - matplotlib=3.5.3
  - pyyaml=6.0.1
  - tqdm
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - torchaudio==0.13.1

      - mujoco==2.3.6
      - dm-control==1.0.13
      - mujoco-python-viewer==0.1.4

      - ray==1.9.2
      - redis==5.0.8

      - transforms3d==0.4.2

      - glfw==2.10.0
      - PyOpenGL==3.1.10
      - imageio==2.31.2